name: Create Monthly Folder

on:
  schedule:
    - cron: "0 7 1 * *"  # Runs at 7:00 AM UTC on the 1st of every month

jobs:
  create-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create year and month folders in blog and images
        run: |
          CURRENT_YEAR=$(date +'%Y')
          CURRENT_MONTH=$(date +'%B')  # Full month name
          
          # Define target directories
          BLOG_DIR="content/blog/$CURRENT_YEAR/$CURRENT_MONTH"
          IMAGE_DIR="static/Images/blog_images/$CURRENT_YEAR/$CURRENT_MONTH"

          # Create the directory structures
          mkdir -p $BLOG_DIR
          mkdir -p $IMAGE_DIR

          # Add placeholder files to ensure folders are tracked in Git
          echo "Folder for $CURRENT_YEAR/$CURRENT_MONTH" > $BLOG_DIR/.placeholder
          echo "Folder for $CURRENT_YEAR/$CURRENT_MONTH" > $IMAGE_DIR/.placeholder

          # Commit and push the changes
          git config --global user.name "Nirav-raval"
          git config --global user.email "niravraval34@gmail.com"
          git add .
          git commit -m "Added folders for $CURRENT_YEAR/$CURRENT_MONTH in blog and images"
          git push
